/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karaoke;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Agustin
 */
public class KaraokeGui extends javax.swing.JFrame {

    /**
     * Creates new form KaraokeJFrame
     */
    public KaraokeGui() {
        this.setUndecorated(true);
        initComponents();
        //setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); //despues descomentar esto
        this.setResizable(false);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int)tk.getScreenSize().getWidth();
        int ysize = (int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
       // getContentPane().setBackground(Color.BLACK);
        //btnDarLaNota.setVisible(false);
       // btnKaraoke.setVisible(false);
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
       /* jPanel1.setFocusable(true);
        jPanel2.setFocusable(true);*/
        this.setFocusable(true);
    }
    
    public void toggleVisiblePanels(int p){
        switch(p){
            case 1:
                jPanel1.setVisible(true);
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                break;
            case 2:
                jPanel1.setVisible(false);
                jPanel2.setVisible(true);
                jPanel3.setVisible(false);
                break;
             case 3:
                jPanel1.setVisible(false);
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                break;     
        }
    }
    /*class ContentPanel extends JPanel {
    Image bgimage = null;

    ContentPanel() {
      MediaTracker mt = new MediaTracker(this);
      bgimage = Toolkit.getDefaultToolkit().getImage("kraoke.png");
      mt.addImage(bgimage, 0);
      try {
        mt.waitForAll();
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }

    protected void paintComponent(Graphics g) {
      super.paintComponent(g);
      int imwidth = bgimage.getWidth(null);
      int imheight = bgimage.getHeight(null);
      g.drawImage(bgimage, 1, 1, null);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new MyJPanel();
        jPanel2 = new MyJPanel2();
        jPanel3 = new MyJPanel3();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.darkGray);

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 0, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    public void setActionListener(ActionListener ac){
       // btnDarLaNota.addActionListener(ac);
       // btnKaraoke.addActionListener(ac);
        
    }
 
    public void setKeyListener(KeyListener ac){
       // btnDarLaNota.addKeyListener(ac);
       // btnKaraoke.addKeyListener(ac);
        jPanel1.addKeyListener(ac);
        jPanel2.addKeyListener(ac);
        this.addKeyListener(ac);
    }
    
     public void rmKeyListener(KeyListener ac){
       // btnDarLaNota.removeKeyListener(ac);
       // btnKaraoke.removeKeyListener(ac);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
